#!/bin/bash
LOCALVER="$(npm list -g node-red | grep node-red | cut -d'@' -f2 | cut -d' ' -f1)"
REMOTEVER="$(npm view node-red version)"
if [ "$LOCALVER" != "$REMOTEVER" ]; then
    echo "Updating Node-RED to version "$REMOTEVER
    npm cache clean
    npm i -g --unsafe-perm node-red
else
    echo "Node-RED is ok at version "$REMOTEVER
fi
